### ISSUE TITLE
Error: RPC_CONNECTION_TIMEOUT

### ISSUE THREAD

**Issue by liklaysh** [Heart-State/com.mirabox.streamdock.discord.sdPlugin#1]
Hi, after update Discord at 26.11.2024 plugin cant connect to Discord
In logs that error

[2024-11-26T18:15:51.969] [ERROR] default - Login failed: Error: RPC_CONNECTION_TIMEOUT
    at Timeout._onTimeout 
(\com.mirabox.streamdock.discord.sdPlugin\plugin\index.js:73:45098)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

In plugin notification - Too many connections, please restart Discord.

**Comment by Heart-State** [comment]
> Hi, after update Discord at 26.11.2024 plugin cant connect to Discord In logs that error
> 
> [2024-11-26T18:15:51.969] [ERROR] default - Login failed: Error: RPC_CONNECTION_TIMEOUT at Timeout._onTimeout (\com.mirabox.streamdock.discord.sdPlugin\plugin\index.js:73:45098) at listOnTimeout (node:internal/timers:564:17) at process.processTimers (node:internal/timers:507:7)
> 
> In plugin notification - Too many connections, please restart Discord.

Yes I found this issue too, I will fix it, thanks for your feedback

**Comment by Heart-State** [comment]
> Hi, after update Discord at 26.11.2024 plugin cant connect to Discord In logs that error
> 
> [2024-11-26T18:15:51.969] [ERROR] default - Login failed: Error: RPC_CONNECTION_TIMEOUT at Timeout._onTimeout (\com.mirabox.streamdock.discord.sdPlugin\plugin\index.js:73:45098) at listOnTimeout (node:internal/timers:564:17) at process.processTimers (node:internal/timers:507:7)
> 
> In plugin notification - Too many connections, please restart Discord.

Hello, could you please tell me if this has happened many times before: Server is running at http://127.0.0.1:3002

**Comment by Heart-State** [comment]
I have found this problem on a colleague's computer, but it does not appear on my computer or the computer next to me. I added exception capture to the computer with the problem, but it did not capture any related exception plug-ins, so I restarted it directly. If the number of restarts is too many, there will be too many connections, and Disocrd will not allow the connection.

**Comment by liklaysh** [comment]
I tried to track the error for a couple of days, as a result, on day 1 there was the same error with a timeout, on other days everything was fine. We need to think about what the problem might be =) Now everything seems to be working ok.

**Comment by Heart-State** [comment]
> I tried to track the error for a couple of days, as a result, on day 1 there was the same error with a timeout, on other days everything was fine. We need to think about what the problem might be =) Now everything seems to be working ok.

OK
