### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by llimonix** [Heart-State/com.mirabox.streamdock.discord.sdPlugin#3]
Would you be willing to post a deobfuscated version of the plugin so that I and other developers can make changes, improve the plugin and add new functionality

**Comment by Heart-State** [comment]
> Would you be willing to post a deobfuscated version of the plugin so that I and other developers can make changes, improve the plugin and add new functionality

I'll go consult.

**Comment by llimonix** [comment]
Thank you so much! I am very glad that you take into account the opinion of the community that uses your devices. I wish you success in your development and work!
